//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_equipo { get; set; }
        public int id_usuario { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
