//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int id { get; set; }
        public int id_proyecto { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaIni { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int id_prioridad { get; set; }
        public bool alcanzada { get; set; }
        public int id_equipo { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Prioridad Prioridad { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
